# Generated by Django 2.0.8 on 2019-05-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
        ('store', '0023_couponuser_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_retirements',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_retreats',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='retreat.Retreat', verbose_name='Applicable retreats'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalcouponuser',
            name='coupon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.Coupon', verbose_name='Coupon'),
        ),
        migrations.AlterField(
            model_name='historicalcouponuser',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalcustompayment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalorderline',
            name='coupon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.Coupon', verbose_name='Applied coupon'),
        ),
        migrations.AlterField(
            model_name='historicalorderline',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentprofile',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalrefund',
            name='orderline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.OrderLine', verbose_name='Orderline'),
        ),
    ]
