# Generated by Django 2.0.8 on 2019-05-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0011_auto_20190527_0447'),
        ('store', '0024_auto_20190527_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retirement',
        ),
        migrations.DeleteModel(
            name='WaitQueue',
        ),
        migrations.DeleteModel(
            name='WaitQueueNotification',
        ),
    ]
